language: cpp
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.4']
      env: COMPILER=g++-4.4

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.6']
      env: COMPILER=g++-4.6

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env: COMPILER=g++-4.8

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: COMPILER=g++-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: COMPILER=g++-5

    - os: linux
      compiler: clang
      env: COMPILER=clang++

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.5']
          packages: ['clang-3.5']
      env: COMPILER=clang++-3.5

    - os: linux
      compiler: gcc
      dist: precise
      env: COMPILER=g++

    - os: osx
      osx_image: xcode9
      env: COMPILER=clang++

    - os: windows

script:
  - echo "script started"
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then 
      chmod +x ./build_unix_tests.sh
      ./build_unix_tests.sh service
      chmod +x ./.run_tests.sh
      ./.run_tests.sh
    else
      chmod +x ./build_unix_tests.sh
      ./build_unix_tests.sh service
      chmod +x ./.run_tests.sh
      ./.run_tests.sh
    fi